# Meta Data for SEO

## Homepage
title = "apio"
titleSeparator = "|"
titleAddition = "Low Code SaaS Platform"
description = "apio is a low code SaaS platform built for small businesses, entrepreneurs and beyond."

## Open Graph + Twitter Cards
images = ["logo_square.png"]
twitterSite = "l1990790120"
twitterCreator = "l1990790120"
facebookAuthor = "l1990790120"
facebookPublisher = "l1990790120"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo_square.png"
schemaTwitter = "https://twitter.com/l1990790120"
schemaLinkedIn = "https://www.linkedin.com/company/apiobuild/"
schemaGitHub = "https://github.com/apiobuild"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = true

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
# footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/h-enk/doks"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
