name: Publish Content
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git config --global user.email "${GITHUB_EMAIL}"
        git config --global user.name "${GITHUB_USER}"
        git fetch --unshallow
        rm -rf public
        echo "checkout to master as worktree"
        git worktree prune && git worktree add -B master public origin/master
        
        echo "generate static content in public"
        docker run --rm -v $(pwd):/site -v $(pwd)/public:/site/public \
          l1990790120/hugo:0.80.0-p "-b 'docs.apiobuild.com' --gc --minify" && \
          npm run build:functions
      env:
        GITHUB_EMAIL: ${{ secrets._GITHUB_EMAIL }}
        GITHUB_USER: ${{ secrets._GITHUB_USER }}  
